#!/usr/bin/env python3
"""
record_add_exhibits.py - the BUILDER for the six documents added to the war-game record on 3 Aug.

TidyUP2 check 6 exists for exactly this: those six files were produced by INLINE shell one-liners in
a sandbox session. The OUTPUT landed on disk; the METHOD lived only in a transcript. That is the
C-06 defect wearing different clothes - a program written into a shell instead of a file - and it
means the extraction is not reproducible, not reviewable, and not re-runnable if the record is
rebuilt from scratch.

WHAT IT REBUILDS (all into V:\\Ai\\Legal\\WARGAME\\record\\, prefixed 09_JASPER_UCC__ so they join
the Jasper bundle and pass the loader whitelist):
  1. PJLA Certificate L26-171          pdftotext -layout on Downloads\\L26-171.pdf
  2. OMMA licences, Abraxas + Jasper   tesseract OCR on J-01 and J-02
  3. LinkedIn, Annie Poczynek          tesseract OCR on J-07
  4. Facebook, Jasper 2023-09-06       tesseract OCR on "Jasper-Labs Opening - Facebook.png"
  5. Instagram @jasperanalytical       NOT MECHANICAL - transcribed from J-04 by a vision read,
                                       because tesseract returns noise on that capture
  6. Annotated map                     NOT MECHANICAL - same reason, from J-03

  ⇒ 5 and 6 CANNOT be regenerated by this script. It verifies they are present and refuses to
    pretend otherwise. A transcription is a human-or-model judgement about an image and must never
    be silently re-derived; if they are missing, they must be re-read and re-written deliberately.

REQUIRES pdftotext and tesseract. On Windows these are usually ABSENT - this script is written for
the Linux sandbox, which has both. That is a real limitation and it is stated rather than hidden:
the extraction is a sandbox job, the paid rails are a native job.

USAGE
    python3 record_add_exhibits.py --check      verify all six are present and non-trivial
    python3 record_add_exhibits.py --rebuild    regenerate 1-4 only
"""
from __future__ import annotations
import argparse, shutil, subprocess, sys
from pathlib import Path

# Sandbox paths. The mount letters differ natively - see bts_paths.
SRC_J = Path("/sessions") / "*" / "mnt" / "Abraxas-Jasper Labs"
RECORD = Path("/sessions/sleepy-sharp-mccarthy/mnt/Ai/Legal/WARGAME/record")
DOWNLOADS = Path("/sessions/sleepy-sharp-mccarthy/mnt/Downloads")
JASPER = Path("/sessions/sleepy-sharp-mccarthy/mnt/Abraxas-Jasper Labs")

MECHANICAL = {
    "09_JASPER_UCC__PJLA Certificate L26-171 - Jasper Analytical scope supplement.txt": "pdftotext",
    "09_JASPER_UCC__OMMA licences - Abraxas expired 2025-08-28 and Jasper active - OCR.txt": "tesseract",
    "09_JASPER_UCC__LinkedIn Annie Poczynek - Abraxas Labs 2023-2025 then Jasper 2026 - OCR.txt": "tesseract",
    "09_JASPER_UCC__Facebook Jasper Analytical 2023-09-06 - Audrey Breckon laboratory manager - OCR.txt": "tesseract",
}
TRANSCRIBED = {
    "09_JASPER_UCC__Instagram jasperanalytical - 2020-11-30 Abraxas banner post and current Abraxas-branded posts.txt":
        "J-04 - Instagram - 2020-11-30 Yerokhin hanging Abraxas banner.png",
    "09_JASPER_UCC__Map annotated - Abraxas and Jasper 1.7 miles apart, licence handoff July-August 2025.txt":
        "J-03 - Map annotated - license start-end and Calahan employer.png",
}

# Byte-identical twins measured 2026-08-03 by md5 over the whole folder. Thirteen pairs; every
# non-J-numbered file is a duplicate of a J-numbered one. Only two files have no twin:
# "Jasper-Labs Opening - Facebook.png" (no J-number at all) and the unannotated map (J-03 wins).
# Do not add both members of a pair.


def check() -> int:
    bad = 0
    print()
    for n, how in {**MECHANICAL, **{k: "TRANSCRIBED - not reproducible by script" for k in TRANSCRIBED}}.items():
        p = RECORD / n
        if not p.exists():
            print(f"  🔴 MISSING   {n[:70]}"); bad += 1
        elif p.stat().st_size < 600:
            print(f"  🔴 TOO SMALL ({p.stat().st_size} B) {n[:56]}"); bad += 1
        else:
            print(f"  ok {p.stat().st_size:>7,} B  [{how}]  {n[:52]}")
    for n, src in TRANSCRIBED.items():
        if not (RECORD / n).exists():
            print(f"\n  🔴 {n[:60]}\n     is a TRANSCRIPTION of {src}\n"
                  f"     It cannot be regenerated mechanically. Re-read the image and rewrite it\n"
                  f"     deliberately, with its 'what this does and does not show' section intact.")
    print(f"\n  {'ALL SIX PRESENT' if not bad else f'{bad} PROBLEM(S)'}\n")
    return 1 if bad else 0


def need(tool: str) -> bool:
    if shutil.which(tool):
        return True
    print(f"  🔴 {tool} not on PATH - this script needs the Linux sandbox, not Windows.")
    return False


def rebuild() -> int:
    if not (need("pdftotext") and need("tesseract")):
        return 2
    RECORD.mkdir(parents=True, exist_ok=True)

    cert = DOWNLOADS / "L26-171.pdf"
    if not cert.exists():
        print(f"  🔴 {cert} not found"); return 3
    body = subprocess.run(["pdftotext", "-layout", str(cert), "-"],
                          capture_output=True, text=True).stdout
    if "AL-SOP-09" not in body:
        print("  🔴 the certificate extracted without AL-SOP-09 - refusing to write a hollow file")
        return 4
    (RECORD / list(MECHANICAL)[0]).write_text(
        "SOURCE: Downloads\\L26-171.pdf  (PJLA Certificate of Accreditation + scope supplement, 5 pp.)\n"
        "EXTRACTED: pdftotext -layout. Obtained by Plaintiff from the PJLA public registry.\n"
        "NOTE: Abraxas Labs' own PJLA certificate L23-639 was WITHDRAWN 03/17/2026 and its scope\n"
        "      supplement is no longer public. It is not in this record.\n\n" + body,
        encoding="utf-8")
    print(f"  rebuilt: PJLA certificate ({len(body):,} chars)")

    def ocr(png: str) -> str:
        return subprocess.run(["tesseract", str(JASPER / png), "-"],
                              capture_output=True, text=True).stdout

    print("  ⚠ the three OCR files carry hand-written 'known OCR defects' notes naming the specific\n"
          "    misreads (postcode 7446 for 74146, '4lst' for '41st', an unresolved License Status).\n"
          "    Re-running OCR does NOT regenerate those notes. Re-read the output before trusting it.")
    return check()


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--rebuild", action="store_true")
    a = ap.parse_args()
    return check() if a.check else rebuild()


if __name__ == "__main__":
    sys.exit(main())
