#!/usr/bin/env python3
"""record_reindex.py - regenerate 00_INDEX.txt for a war-game record directory.

WHY THIS EXISTS
---------------
`wargame_feed.py` writes `00_INDEX.txt` as part of a build. Nothing else does. But two
tools mutate a record directory AFTER the build:

  * `record_trim.py`        - drops near-duplicates and moves originals to `_orig\`
  * `record_add_exhibits.py`- adds documents that were never in any feed

Neither regenerates the index. So on 2026-08-03 the record grew to 74 documents while
`00_INDEX.txt` went on saying "71 documents" and omitting all six exhibits added that
day - every one of which bears on the transfer requests. A paid reader handed that
index sees a record that does not contain the thing it is being asked about, and
answers confidently about the wrong file set. That is S-117 / C-12 exactly: presence
is not coverage, and an index nobody regenerates is a coverage claim nobody checked.

  MEASURED 2026-08-08, before this tool existed:
    record/       74 documents present, 71 listed, 7 unlisted, 4 listed-but-absent
    record_core/  51 documents present, index state unverified

DESIGN NOTES
------------
* The shuffle is deliberate and is preserved. A fixed running order is an argument
  about what matters; the record must not carry one. Seed is recorded in the header
  so a listing can be reproduced exactly.
* No document is summarized. A one-line summary of a document is an argument about it.
* `--check` reports drift and writes nothing. Call it from TidyUP; it exits non-zero
  on drift, so a stale index goes RED instead of going unnoticed.
* Truncation control on every read: bytes consumed vs bytes declared by stat(). The
  sandbox mount has served short reads thirteen times, and a silently truncated
  document would be indexed at the wrong length with a confident SHA beside it.
"""
from __future__ import annotations

import argparse
import hashlib
import random
import sys
from pathlib import Path

INDEX_NAME = "00_INDEX.txt"


def _resolve(win: str, tail: str) -> Path:
    p = Path(win)
    if p.exists():
        return p
    for c in Path("/sessions").glob(f"*/mnt/{tail}"):
        return c
    return p


DEFAULT = _resolve(r"V:\Ai\Legal\WARGAME\record", "Ai/Legal/WARGAME/record")


class Truncated(RuntimeError):
    pass


def read_verified(p: Path) -> str:
    """Read, and refuse to believe a short read."""
    declared = p.stat().st_size
    raw = p.read_bytes()
    if len(raw) != declared:
        raise Truncated(f"{p.name}: stat says {declared} B, read returned {len(raw)} B")
    return raw.decode("utf-8", errors="replace")


def scan(rec: Path) -> list[tuple[str, str, int]]:
    rows: list[tuple[str, str, int]] = []
    for p in sorted(rec.glob("*.txt")):
        if p.name == INDEX_NAME:
            continue
        txt = read_verified(p)
        rows.append((p.name, hashlib.sha256(txt.encode()).hexdigest()[:12], len(txt)))
    return rows


def listed(rec: Path) -> set[str]:
    idx = rec / INDEX_NAME
    if not idx.exists():
        return set()
    lines = idx.read_text(encoding="utf-8", errors="replace").splitlines()
    try:
        start = next(i for i, l in enumerate(lines) if set(l.strip()) == {"-"}) + 1
    except StopIteration:
        return set()
    out: set[str] = set()
    for l in lines[start:]:
        if not l.strip():
            continue
        # FILE is left-padded to a fixed width, then SHA (12 hex) then BYTES
        parts = l.rsplit(None, 2)
        if len(parts) == 3 and len(parts[1]) == 12:
            out.add(parts[0].strip())
        else:
            out.add(l.strip())
    return out


def render(rows: list[tuple[str, str, int]], seed: int) -> str:
    total = sum(sz for _, _, sz in rows)
    shuffled = rows[:]
    random.Random(seed).shuffle(shuffled)
    head = [
        "THE RECORD - Chambers v. Abraxas Labs, LLC, CJ-2025-1618",
        "District Court of Tulsa County, Oklahoma. Non-jury trial.",
        "",
        f"{len(rows)} documents. {total:,} characters.",
        "",
        "Pleadings, written discovery, documents produced by the parties, and exhibits.",
        "",
        "This list is in NO significant order. It is shuffled deliberately, so that no reader",
        "inherits a running order that implies a narrative. No document is summarized here,",
        "because a one-line summary of a document is an argument about it.",
        "",
        "Read what you need. Every read is logged.",
        "",
        f"Index regenerated by record_reindex.py (seed={seed}). The record directory is the",
        "authority; this file is derived from it and is rebuilt, never hand-edited.",
        "",
        f"{'FILE':<80} {'SHA256':<14} BYTES",
        "-" * 104,
    ]
    return "\n".join(head + [f"{n:<80} {h:<14} {sz}" for n, h, sz in shuffled]) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--record", default=str(DEFAULT), help="record directory to index")
    ap.add_argument("--check", action="store_true",
                    help="report drift, write nothing, exit 1 if stale")
    ap.add_argument("--seed", type=int, default=20260808)
    a = ap.parse_args()

    rec = Path(a.record)
    if not rec.is_dir():
        print(f"  no such record directory: {rec}")
        return 2

    try:
        rows = scan(rec)
    except Truncated as e:
        print(f"\n  TRUNCATED READ - refusing to index: {e}")
        print("  An index built on a short read states a wrong length beside a confident SHA.\n")
        return 2

    if not rows:
        print(f"  {rec} holds no .txt documents - refusing to write an empty index.")
        return 2

    was = listed(rec)
    now = {n for n, _, _ in rows}
    unlisted, absent = now - was, was - now

    print(f"  record       : {rec}")
    print(f"  present      : {len(now)}")
    print(f"  listed       : {len(was)}")
    print(f"  unlisted     : {len(unlisted)}")
    print(f"  listed/absent: {len(absent)}")
    for n in sorted(unlisted):
        print(f"    + {n}")
    for n in sorted(absent):
        print(f"    - {n}")

    if a.check:
        drift = bool(unlisted or absent)
        print("\n  STALE - run without --check to rebuild.\n" if drift
              else "\n  index matches the directory.\n")
        return 1 if drift else 0

    (rec / INDEX_NAME).write_text(render(rows, a.seed), encoding="utf-8")
    total = sum(sz for _, _, sz in rows)
    print(f"\n  wrote {INDEX_NAME}: {len(rows)} documents, {total:,} chars, "
          f"~{total // 4:,} tokens (seed={a.seed})\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
