#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tools_sync.py - THE GENERATOR THAT DID NOT EXIST. PLM-15. Cowork, 2026-08-12.

THE DEFECT, IN ITS OWN WORDS
---------------------------
`00_TOOLS_INDEX.md` has carried this correction since 2026-07-16:

    "Generated from the JSON. Edit the JSON, not this page" WAS FALSE. No generator
    exists. Nothing on disk reads TOOLS_REGISTRY.json and writes this page. So anyone who
    followed that instruction edited the JSON and this page silently did not change.

Both files have been hand-maintained ever since, and they have drifted **in both
directions, five times**: `bts_identity` (07-15, registry only), `bts_tools` (07-28, page
only - which is how an MCP server got built that reimplemented 7 of its 8 verbs), and
`maint_sweep`, `disk_guard`, `tidyup2_full` in one night (registry only, three times, by
the session that was citing the first two at other people's code).

  ==> "EDIT BOTH FILES IN THE SAME TURN" IS NOT A MECHANISM. IT IS A HOPE, AND IT HAS
      NOW FAILED FIVE TIMES. Two hand-maintained copies of one list is the copies-rot
      defect, and the fix for copies-rot is never more discipline.

WHY THIS IS NOT A NAIVE GENERATOR
---------------------------------
The obvious build - render the page FROM the JSON - destroys the thing that makes the
page worth reading. Keith's own condition, recorded on the loose-ends list: *"it must
preserve this page's narrative, which is not in the JSON."* The page carries why a tool
exists, what it cost to learn, which scar it closes. The JSON carries fields.

So this generates ONE BLOCK and touches nothing else:

    <!-- BEGIN GENERATED TOOL LIST -->   ... every registry id, name, class, conf ...
    <!-- END GENERATED TOOL LIST -->

Everything outside those markers is hand-written and never rewritten. The block is the
COMPLETENESS guarantee; the narrative above it is the meaning. Drift becomes impossible
in the direction that has actually hurt - a tool in the registry and nowhere on the page.

  ==> AND IT CLOSES PLM-45 STRUCTURALLY. Registration was two actions in two files, and
      TidyUP registers tools at step 7 while TidyUP2 runs at step 14, so any tool built
      during verification missed the step. With this, registration is ONE action - write
      the JSON - and the page follows. An ordering defect cannot bite a single step.

USAGE
    py -3.14 tools_sync.py --check     # exit 1 on drift. Writes nothing.
    py -3.14 tools_sync.py --write     # regenerate the block
    py -3.14 tools_sync.py --selftest  # negative controls
"""
from __future__ import annotations

import json
import pathlib
import re
import shutil
import sys

MESH = pathlib.Path(__file__).resolve().parent
REG = MESH / "TOOLS_REGISTRY.json"
IDX = MESH.parent / "00_TOOLS_INDEX.md"

BEGIN = "<!-- BEGIN GENERATED TOOL LIST -->"
END = "<!-- END GENERATED TOOL LIST -->"

HEADER = """
---

%s
<!-- Regenerated by BTS_MESH\\tools_sync.py from TOOLS_REGISTRY.json.
     DO NOT HAND-EDIT BETWEEN THE MARKERS - your edit will be overwritten.
     Everything OUTSIDE the markers is hand-written narrative and is never touched. -->

## THE COMPLETE LIST — generated, so it cannot silently disagree with the registry

> **Why this block exists.** The narrative above explains what tools MEAN; it is written
> by hand and is the reason this page is worth reading. This block guarantees the page is
> COMPLETE. Both files were hand-maintained for a month and drifted five times, twice
> causing a tool to be rebuilt from scratch. The prose is the point; the completeness is
> the check.

| id | class | conf | tool |
|---|---|---|---|
"""


def load():
    raw = REG.read_bytes()
    if len(raw) != REG.stat().st_size:
        raise SystemExit("REFUSING: short read on the registry")
    return json.loads(raw.decode("utf-8"))["tools"]


def render(tools) -> str:
    rows = []
    for t in sorted(tools, key=lambda x: x["id"].lower()):
        name = str(t.get("name", "")).replace("|", "\\|")
        if len(name) > 110:
            name = name[:107] + "..."
        rows.append("| `%s` | %s | %s | %s |"
                    % (t["id"], t.get("class", "—"), t.get("conf", "—"), name))
    return (HEADER % BEGIN) + "\n".join(rows) + "\n\n%s\n" % END


def _lf(s: str) -> str:
    """Normalize line endings before ANY comparison.

    🔴 THIRD TIME TONIGHT. `Path.write_text` translates "\\n" -> "\\r\\n" on Windows, and
    `read_text`/`decode` gives it back either way, so a block written from a "\\n" string
    never equals the "\\n" string that produced it. The first version of this generator
    wrote the file correctly and then reported ITSELF as still drifting - "it lists 2
    tool(s), the registry holds 2", counts matching, verdict STALE - which is as clear a
    statement as a checker can make that the fault is in the comparison, not the data.

    Same root cause as `maint_sweep`'s truncation control flagging six healthy files.
    ⇒ COMPARE TEXT AS TEXT (normalized) OR BYTES AS BYTES. Never one against the other.
    """
    return s.replace("\r\n", "\n").replace("\r", "\n")


def current_block(text: str):
    text = _lf(text)
    i, j = text.find(BEGIN), text.find(END)
    if i == -1 or j == -1:
        return None
    return text[i:j + len(END)]


def check(verbose=True):
    """Return a list of problems. EMPTY means the page is complete."""
    tools = load()
    text = IDX.read_bytes().decode("utf-8", "replace")
    problems = []

    # 1. Completeness: every registry id must appear SOMEWHERE on the page.
    low = text.lower()
    missing = [t["id"] for t in tools if t["id"].lower() not in low]
    for m in missing:
        problems.append("registry has '%s' and the index page never mentions it" % m)

    # 2. The generated block must match what the registry would produce right now.
    want = render(tools)
    have = current_block(text)
    if have is None:
        problems.append("the generated block is ABSENT from the index page")
    else:
        want_block = current_block(want)
        if _lf(have).strip() != _lf(want_block).strip():
            n_have = len(re.findall(r"^\| `", have, re.M))
            problems.append("the generated block is STALE: it lists %d tool(s), the "
                            "registry holds %d" % (n_have, len(tools)))

    if verbose:
        print("  registry tools        : %d" % len(tools))
        print("  index page bytes      : %s" % format(len(text), ","))
        print("  generated block       : %s"
              % ("present" if have else "ABSENT"))
        for p in problems:
            print("  DRIFT  %s" % p)
        if not problems:
            print("  ok     every registry tool appears on the page, block is current")
    return problems


def write():
    tools = load()
    text = _lf(IDX.read_bytes().decode("utf-8", "replace"))
    block = render(tools)
    i, j = text.find(BEGIN), text.find(END)
    if i != -1 and j != -1:
        # Replace only between the markers, keeping the '---' separator we emit.
        start = text.rfind("\n---\n", 0, i)
        start = start if start != -1 else i
        new = text[:start] + block
        tail = text[j + len(END):]
        new += tail
    else:
        new = text.rstrip() + "\n" + block
    shutil.copy2(IDX, IDX.with_suffix(".md.tools_sync.bak"))
    # newline="" — write the bytes we composed, with no translation. See _lf().
    with open(IDX, "w", encoding="utf-8", newline="") as fh:
        fh.write(new)
    # ASSERT THE ARTIFACT: re-read from disk and re-check.
    problems = check(verbose=False)
    print("  wrote %s (%s bytes)" % (IDX.name, format(IDX.stat().st_size, ",")))
    print("  re-checked from disk: %s"
          % ("CLEAN" if not problems else "STILL DRIFTING: %s" % problems))
    return problems


def selftest() -> int:
    """A generator that has never been shown to CATCH drift is a formatter."""
    import tempfile
    global REG, IDX
    real_reg, real_idx = REG, IDX
    checks = []
    try:
        d = pathlib.Path(tempfile.mkdtemp(prefix="toolsync_"))
        REG = d / "TOOLS_REGISTRY.json"
        IDX = d / "00_TOOLS_INDEX.md"
        REG.write_text(json.dumps({"tools": [
            {"id": "alpha", "name": "alpha - first", "class": "TOOL", "conf": "V"},
            {"id": "beta", "name": "beta - second", "class": "TEST", "conf": "U"},
        ]}), encoding="utf-8")

        IDX.write_text("# narrative\n\nSome hand-written prose about alpha and beta.\n",
                       encoding="utf-8")
        checks.append(("a page with NO generated block is reported as drifting",
                       bool(check(verbose=False))))

        write()
        checks.append(("after --write the page is clean", not check(verbose=False)))

        txt = IDX.read_text(encoding="utf-8")
        checks.append(("the hand-written narrative SURVIVED the write",
                       "Some hand-written prose" in txt))

        # Add a tool to the registry only - the drift that has actually hurt.
        reg = json.loads(REG.read_text(encoding="utf-8"))
        reg["tools"].append({"id": "gamma", "name": "gamma - added to the registry only",
                             "class": "TOOL", "conf": "U"})
        REG.write_text(json.dumps(reg), encoding="utf-8")
        probs = check(verbose=False)
        checks.append(("a tool added to the REGISTRY ONLY is caught", bool(probs)))
        checks.append(("and it is named in the finding",
                       any("gamma" in p for p in probs)))

        write()
        checks.append(("--write closes that drift", not check(verbose=False)))
        checks.append(("narrative still intact after the second write",
                       "Some hand-written prose" in IDX.read_text(encoding="utf-8")))
    finally:
        REG, IDX = real_reg, real_idx

    print("=" * 78)
    print("  tools_sync --selftest")
    print("=" * 78)
    for label, good in checks:
        print("  %s  %s" % ("OK  " if good else "FAIL", label))
    bad = [l for l, g in checks if not g]
    print("SELFTEST PASS - it catches registry-only drift and preserves the narrative."
          if not bad else "SELFTEST FAIL - %d check(s)." % len(bad))
    return 1 if bad else 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    if "--write" in sys.argv:
        sys.exit(1 if write() else 0)
    print("=" * 78)
    print("  tools_sync --check")
    print("=" * 78)
    sys.exit(1 if check() else 0)
